name: CI

on:
  push:

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: python -m unittest tests.test_circle
      - run: python -m unittest tests.test_rectangle
      - run: python -m unittest tests.test_square
      - run: python -m unittest tests.test_triangle

  windows_test:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: python -m unittest tests.test_circle
      - run: python -m unittest tests.test_rectangle
      - run: python -m unittest tests.test_square
      - run: python -m unittest tests.test_triangle
